### ISSUE TITLE
Error setup paso 10: PG::ConnectionBad could not connect to server

### ISSUE THREAD

**Issue by smrebolledo** [IIC2143-2021-1/Syllabus#17]
hola, cuando escribo en consola rails db:create me sale este error
![Captura de pantalla (9)](https://user-images.githubusercontent.com/42575575/112695804-7887bc00-8e63-11eb-8074-f97b6526ac67.png)

**Comment by meretamal** [comment]
Hola, eso es porque no tienes un servicio de postgres corriendo.

Para hacerlo, ejecuta `sudo service postgresql start` y luego sigue con el paso 10

**Comment by smrebolledo** [comment]
Si lo hice e igual me tira ese mismo error

**Comment by meretamal** [comment]
Puedes mandar el output del comando anterior?

**Comment by smrebolledo** [comment]
Tuve que cerrar la terminal por eso está desde ahí, pero antes de eso todo me resultó bien
![Captura de pantalla (10)](https://user-images.githubusercontent.com/42575575/112708220-9703ac80-8e8f-11eb-9529-5791331409d4.png)

**Comment by meretamal** [comment]
Puedes ejecutar `pg_lsclusters`  y mandar el output?

**Comment by smrebolledo** [comment]
![image](https://user-images.githubusercontent.com/42575575/112708568-73d9fc80-8e91-11eb-9432-373271fcf3e7.png)

**Comment by meretamal** [comment]
perf, eso es porque el servidor está corriendo en el puerto 5433, y en el archivo de **database.yml**, como no se especifica el puerto, toma el puerto por _default_, que es el 5432.

Para solucionarlo agrega una variable de entorno en tu archivo **.env** llamada `DB_PORT` que sea igual a 5433, y reemplaza el contenido de **database.yml** por:

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <nombre proyecto>_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>

test:
  <<: *default
  database: <nombre proyecto>_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
```
